trigger:
- none

pool:
  name: irfank

steps:
- task: FortifySCA@7
  inputs:
    applicationType: 'java'
    buildToolOptions: '.'
    fortifyBuildId: 'test'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'fortifyssc'
    fortifyApplicationName: 'deneme'
    fortifyApplicationVersion: 'maven'

- task: CmdLine@2
  inputs:
    script: |
        python socars_test.py
              --ssc-url "https://192.168.13.177:8443/ssc" 
              --ssc-token "ZTRmMzZlNWQtNzRlOS00NGM3LTk1ZWMtN2FjZTFjYzFhYzM2" 
              --project-name "deneme"
              --version-name "maven"
              --smtp-server "192.168.13.181"
              --smtp-port "25"
              --from-address "smpttest@gmail.com"
              --to-address "irfankaraduman10@gmail.com"
              --fail-on-issues
    workingDirectory: "C:\Program Files\azure-agent"
  


